### PR TITLE
Always return the same number of values from _initiate_authentication()

### LINKED ISSUE #157: Duo authentication not working with later versions of aws-adfs
I receive the following error when using aws-adfs version 1.24.1 with duo enabled.

Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/login.py", line 167, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config, config.adfs_user, password)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 34, in authenticate
    principal_roles, assertion, aws_session_duration = extract_strategy()
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 114, in extract
    return duo_auth.extract(html_response, config.ssl_verification, config.u2f_trigger_default, session)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/_duo_authenticator.py", line 54, in extract
    ssl_verification_enabled
ValueError: not enough values to unpack (expected 4, got 3)

When I am using aws-adfs version 1.12.3 the duo push authentication works fine.

I am using the following login command.

aws-adfs login --adfs-host=my.adfs.host --ssl-verification --session-duration 14400 --no-sspi

### PR DESCRIPTION
**Pull request by pdecat**
This PR aims to resolve #157.

The issue was introduced by #127 : https://github.com/venth/aws-adfs/pull/127/files#diff-0584fbc181c07f609204d3aa5779348fR482

### CODE REVIEW

**Comment by psiri** [comment]
When on DUO bypass networks, this fix does not properly return roles the user has access to and ultimately still fails but at a different step than before:
`2020-03-11 19:44:08,170 [authenticator authenticator.py:authenticate] [10420-MainProcess] [4516314560-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Password: 
Sending request for authentication
2020-03-11 19:44:16,241 [authenticator authenticator.py:authenticate] [10420-MainProcess] [4516314560-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
This account does not have access to any roles`

With verbose logging:
`2020-03-11 19:48:08,488 [authenticator authenticator.py:authenticate] [10551-MainProcess] [4408692160-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
2020-03-11 19:48:08,488 [authenticator authenticator.py:authenticate] [10551-MainProcess] [4408692160-MainThread] - DEBUG: Roles along with principals found after authentication: None
This account does not have access to any roles`

Immediately upon disconnecting from DUO bypass networks, user can authenticate properly again and is presented with all accounts/roles.

**Comment by pdecat** [comment]
Hi @psiri, can you try with `--no-sspi` ?

**Comment by psiri** [comment]
> Hi @psiri, can you try with `--no-sspi` ?

Previously did try this with the same result, but for reference:
`➜  ~ aws-adfs login --<MY-ADFS> --profile=default --ssl-verification --region=us-west-2 --no-sspi
2020-03-12 08:37:26,980 [authenticator authenticator.py:authenticate] [15070-MainProcess] [4558478784-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Password: 
Sending request for authentication
2020-03-12 08:37:34,450 [authenticator authenticator.py:authenticate] [15070-MainProcess] [4558478784-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
This account does not have access to any roles
`

**Comment by pdecat** [comment]
I've removed the WIP status as, at least, this PR resolves the original issue that masked the underlying error.

@psiri you should be able to get more details about what's going on by adding `--verbose` to your `aws-adfs login` command, e.g. `aws-adfs --verbose login ...`.

**Comment by venth** [comment]
Thanks @pdecat 👍  Released with version: 1.24.3. Sorry for the delay.

**Pull request merged**
