### PR TITLE
Default to 'default' profile, in line with other AWS tools.

### PR DESCRIPTION
**Pull request by brandond**
This might be a breaking change for some folks, but I think it's important to work the same as other AWS CLI tools that all work with the 'default' profile if the --profile option or AWS_DEFAULT_PROFILE environment variable are not set.

This change also makes it honor the AWS_DEFAULT_PROFILE environment variable, which it does not currently do.

### CODE REVIEW

**Comment by brandond** [comment]
Actually, let me take a longer look at this. I think I can probably replace a lot of the current `_load_adfs_config_from_stored_profile` functionality with stuff already provided by `botocore.session`

**Comment by venth** [comment]
I'm OK with the change. It makes sense to stick to aws cli behavior. I'll be little unresponsive. I've caught sinusitis.

**Comment by brandond** [comment]
Ahh that sucks, hope you feel better soon :( I'll comment again when I have something ready for review.

**Comment by venth** [comment]
OK

**Comment by venth** [comment]
Hi @brandond, do you want me to merge this request?

**Comment by brandond** [comment]
@venth go ahead and take it as-is; I still might take a shot at centralizing the config load/store stuff into one place, but I don't have the time for it at the moment. I'll open a new PR when I do.

**Comment by venth** [comment]
merged

**Pull request merged**
