### PR TITLE
Allow to specify SAML response from local file

### PR DESCRIPTION
**Pull request by avoidik**
This could be useful for debugging and configuring unknown (or broken) 2FA providers

### CODE REVIEW

**Comment by avoidik** [comment]
`aws-adfs login --assertfile ./response.dat --adfs-host adfs.host.net`

**Comment by venth** [comment]
Thanks 👍

**Comment by stewmi** [comment]
Would it be possible to get an example of the workflow to use this workaround?  you get the SAML response from UI and then place it in .`/response.dat` ?  Running into same issue so just confirming.

**Comment by avoidik** [comment]
Yes, that's right. Just put raw Base64 encoded SAML response to a file. You
could get the SAML response with Fiddler, or by using Firefox extension
called SAML-tracer.

**Comment by stewmi** [comment]
Thanks!

**Pull request merged**
