### PR TITLE
Do not print stack trace if no U2F device is available

### PR DESCRIPTION
**Pull request by pdecat**
This PR avoids printing a stack trace if U2F is reported as supported by Duo but no U2F device is plugged.

Note: it did not prevent the default authentication method from working concurrently.

Also, it will properly terminate the aws-adfs process if all authentication methods were cancelled.
Before, it used to be necessary to manually terminate the process, e.g with `Ctrl-C`:
```
# rm ~/.aws/adfs_cookies
# username=****** aws-adfs login --env --profile=****** --region=eu-west-1 --adfs-host=****** --ssl-verification --session-duration=14400 --no-sspi
2019-11-15 14:25:27,742 [authenticator authenticator.py:authenticate] [1909-MainProcess] [140653257566016-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Failed to read password from env
Password:
Sending request for authentication
Waiting for additional authentication
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/patrick/workspaces/aws/aws-adfs/aws_adfs/_duo_authenticator.py", line 127, in _perform_authentication_transaction
    ssl_verification_enabled,
  File "/home/patrick/workspaces/aws/aws-adfs/aws_adfs/_duo_authenticator.py", line 347, in _verify_authentication_status
    raise click.ClickException("No FIDO U2F authenticator is eligible.")
click.exceptions.ClickException: No FIDO U2F authenticator is eligible.
^C
Aborted!
```

### CODE REVIEW

**Comment by pdecat** [comment]
Test with not U2F key plugged and default method disabled:

```
rm ~/.aws/adfs_cookies && aws-adfs-claranet --no-u2f-trigger-default
2019-11-15 15:35:50,022 [authenticator authenticator.py:authenticate] [5578-MainProcess] [140113789003584-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Failed to read password from env
Password: 
Sending request for authentication
Waiting for additional authentication
No FIDO U2F authenticator is eligible.
All authentication methods cancelled, aborting.
```

**Comment by pdecat** [comment]
Test with not U2F key plugged and default method enabled:

```
2019-11-15 15:38:30,116 [authenticator authenticator.py:authenticate] [14160-MainProcess] [139676636796736-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Failed to read password from env
Password: 
Sending request for authentication
Waiting for additional authentication
Triggering default authentication method: 'Duo Push'
No FIDO U2F authenticator is eligible.
Going for aws roles

        Prepared ADFS configuration as follows:
[...]
```

**Comment by pdecat** [comment]
Test with a U2F key plugged, default method enabled and activating the U2F key:

```
# rm ~/.aws/adfs_cookies && aws-adfs-claranet --u2f-trigger-default
2019-11-15 15:58:09,659 [authenticator authenticator.py:authenticate] [12343-MainProcess] [139925249513280-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Failed to read password from env
Password: 
Sending request for authentication
Waiting for additional authentication
Triggering default authentication method: 'Duo Push'
Activate your FIDO U2F authenticator now: 'CtapHidDevice(/dev/hidraw3)'
Got response from FIDO U2F authenticator: 'CtapHidDevice(/dev/hidraw3)'
Going for aws roles

        Prepared ADFS configuration as follows:
[...]
```

**Comment by pdecat** [comment]
Test with a U2F key plugged, default method enabled and responding to the Duo Push:

```
# rm ~/.aws/adfs_cookies && # username=****** aws-adfs login --env --profile=****** --region=eu-west-1 --adfs-host=****** --ssl-verification --session-duration=14400 --no-sspi --u2f-trigger-default
2019-11-15 16:00:07,821 [authenticator authenticator.py:authenticate] [18304-MainProcess] [139777998063424-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Failed to read password from env
Password: 
Sending request for authentication
Waiting for additional authentication
Triggering default authentication method: 'Duo Push'
Activate your FIDO U2F authenticator now: 'CtapHidDevice(/dev/hidraw3)'
Going for aws roles

        Prepared ADFS configuration as follows:
[...]
```

**Comment by venth** [comment]
Thanks @pdecat 👍 Released with version 1.19.1

**Comment by pdecat** [comment]
Thank you @venth!

**Pull request merged**
